version: "3.5"
services:
  redis-standalone:
    image: "redis:6.0-alpine"
    restart: always
    ports:
      - "6378:6379"
    networks:
      - redis_standalone_subnet
    volumes:
      - ./data:/data

networks:
  redis_standalone_subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
